In [4]:
import pickle
import numpy as np

In [23]:
rede_neural = pickle.load(open('./assets/rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('./assets/arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('./assets/svm_finalizado.sav', 'rb'))

In [5]:
with open( './assets/credit.pkl', 'rb') as f:
    X_credit_treinamento, Y_credit_treinamento,    X_credit_teste, Y_credit_teste = pickle.load(f)
    
with open( './assets/census.pkl', 'rb') as f:
    X_census_treinamento, Y_census_treinamento, X_census_teste, Y_census_teste = pickle.load(f)

In [7]:
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
Y_credit = np.concatenate((Y_credit_treinamento, Y_credit_teste), axis = 0)

In [8]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1, -1)
novo_registro, novo_registro.shape

(array([[-1.3754462 ,  0.50630999,  0.10980934]]), (1, 3))

In [9]:
rede_neural = rede_neural.fit(X_credit, Y_credit)
arvore = arvore.fit(X_credit, Y_credit)
svm = svm.fit(X_credit, Y_credit)

c:\users\matheuan\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [10]:
resp_rede_neural = rede_neural.predict(novo_registro)
resp_arvore = arvore.predict(novo_registro)
resp_svm = svm.predict(novo_registro)

In [11]:
#Podemos comparar o resultado de cada algoritmo
resp_rede_neural[0], resp_arvore[0], resp_svm[0]


(0, 0, 0)

In [12]:
paga = 0
nao_paga = 0

if resp_rede_neural[0] ==1:
    nao_paga += 1
else:
    paga += 1
    
if resp_arvore[0] ==1:
    nao_paga += 1
else:
    paga += 1
    
if resp_svm[0] ==1:
    nao_paga += 1
else:
    paga += 1

    if paga > nao_paga:
        print("cliente paga")
    elif paga == nao_paga:
        print("empate")
    else:
        print("cliente não paga")

cliente paga


    Rejeição de classificadores

In [24]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1, -1)
novo_registro, novo_registro.shape

(array([[-1.3754462 ,  0.50630999,  0.10980934]]), (1, 3))

In [25]:
resp_rede_neural = rede_neural.predict(novo_registro)
resp_arvore = arvore.predict(novo_registro)
resp_svm = svm.predict(novo_registro)

In [26]:
prob_rede_neural = rede_neural.predict_proba(novo_registro)
prob_rede_neural

array([[1.000000e+00, 4.965757e-17]])

In [27]:
conf_rede_neural = prob_rede_neural.max()
conf_rede_neural

1.0

In [28]:
prob_arvore = arvore.predict_proba(novo_registro)
conf_arvore = prob_arvore.max()
conf_arvore


1.0

In [29]:
prob_svm = svm.predict_proba(novo_registro)
conf_svm = prob_svm.max()
conf_svm


0.9999977364176479